//! Vertical datums of DEM layers, and the on-the-fly height correction that
//! brings every layer of a source onto the datum its geoid expects.
//!
//! # Model
//!
//! - A source's **target datum** follows from its geoid model
//!   ([`GeoidModel::target_datum`]): GSIGEO2011 → JGD2011,
//!   JPGEO2024+Hrefconv2024 → JGD2024. The geoid is still added once, at the
//!   end, exactly as before.
//! - Every DEM **layer** has a datum: the layer's `verticalDatum`, else the
//!   source's `verticalDatum` (so a whole stack is declared at once).
//! - The **base** DEM has a [`BaseDatum`]: a real upstream is `jgd2011` /
//!   `jgd2024` only when the operator says so (`DEM_VERTICAL_DATUM`); the
//!   sea-level base is [`BaseDatum::Agnostic`] — "no data → 0 m = mean sea
//!   level" is not a JGD2011 or JGD2024 height and is never corrected.
//! - A layer (or the base) whose datum differs from the target gets
//!   `ΔH(p)` added to each of its elevations **before** the priority composite
//!   (`paint_over`), so the composite is homogeneous. ΔH comes from a
//!   correction **product** the source names by its manifest URL
//!   (`heightCorrection.manifest`), e.g. GSI's JGD2011 → JGD2024 標高補正
//!   parameters as published by `tile/scripts/vertical-cogs`.
//! - Anything that cannot be served correctly is refused when the config is
//!   loaded ([`plan_source`]) — a datum with no correction to the target, an
//!   inverse correction we do not have, a geoid without a datum, an unknown
//!   base under a correction — rather than passed through.
//!
//! A source that declares none of this (`verticalDatum`, `heightCorrection`)
//! is untouched: [`DatumPlan::Legacy`] builds exactly the provider it always
//! did, with the same cache keys.
//!
//! # Sampling
//!
//! [`sample`] and [`DhProduct::sample`] are a line-by-line port of the
//! normative reference `tile/scripts/vertical-cogs/sampler.py` (`sample`,
//! `mesh6_of`, `DhGsi`); the golden test pins them to vectors generated by it.

use std::collections::HashMap;
use std::fmt;
use std::str::FromStr;
use std::sync::{Arc, OnceLock};

use object_store::{
    ObjectStore, ObjectStoreExt, local::LocalFileSystem, memory::InMemory, path::Path as ObjectPath,
};
use serde::Deserialize;
use sha2::{Digest, Sha256};
use url::Url;
use xxhash_rust::xxh64::xxh64;

use super::dem::{DemTile, PixelPositions};
use super::geoid::GeoidModel;
use crate::cog::{CogReader, Float32Raster};

// ─────────────────────────────── Datums ───────────────────────────────

/// An orthometric-height datum (the 標高 a DEM value is expressed in).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VerticalDatum {
    /// 測地成果2011 heights.
    Jgd2011,
    /// 測地成果2024 heights (GSI's 2025 標高改定).
    Jgd2024,
}

impl VerticalDatum {
    pub fn slug(&self) -> &'static str {
        match self {
            Self::Jgd2011 => "jgd2011",
            Self::Jgd2024 => "jgd2024",
        }
    }
}

impl fmt::Display for VerticalDatum {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.slug())
    }
}

impl FromStr for VerticalDatum {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.trim().to_ascii_lowercase().as_str() {
            "jgd2011" => Ok(Self::Jgd2011),
            "jgd2024" => Ok(Self::Jgd2024),
            other => Err(format!(
                "unknown vertical datum `{other}` (valid: jgd2011, jgd2024)"
            )),
        }
    }
}

/// Datum of the shared base DEM (`DEM_URL`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BaseDatum {
    /// Declared by the operator (`DEM_VERTICAL_DATUM`).
    Known(VerticalDatum),
    /// The sea-level base: "no data → 0 m orthometric = mean sea level". It is
    /// not a height in either datum, so it is never corrected — adding ±0.4 m
    /// of ΔH would warp the sea surface.
    Agnostic,
    /// A real upstream whose datum nobody declared. Sources that apply a
    /// correction refuse to build on it.
    Unknown,
}

impl BaseDatum {
    /// Resolve the base datum for `DEM_URL` (`is_sea_level`) and the
    /// `DEM_VERTICAL_DATUM` env value.
    pub fn resolve(is_sea_level: bool, declared: Option<&str>) -> Self {
        let declared = declared.map(str::trim).filter(|s| !s.is_empty());
        if is_sea_level {
            if let Some(d) = declared {
                tracing::warn!(
                    DEM_VERTICAL_DATUM = %d,
                    "ignored: the sea-level base is datum-agnostic and is never height-corrected"
                );
            }
            return Self::Agnostic;
        }
        match declared.map(str::parse::<VerticalDatum>) {
            None => Self::Unknown,
            Some(Ok(d)) => Self::Known(d),
            Some(Err(e)) => {
                tracing::error!(
                    error = %e,
                    "DEM_VERTICAL_DATUM is invalid; the base DEM datum is treated as unknown \
                     and sources with a heightCorrection will be refused"
                );
                Self::Unknown
            }
        }
    }

    fn slug(&self) -> &'static str {
        match self {
            Self::Known(d) => d.slug(),
            Self::Agnostic => "agnostic",
            Self::Unknown => "unknown",
        }
    }
}

/// What to do with an elevation that needs a correction where the product has
/// no ΔH (outside its grids: the Northern Territories, Iwo-to, the Senkaku
/// islands, Nanatsu-jima, the open sea, …).
///
/// **Pending a policy decision** — `keep` is the default only because it does
/// not change what is served today; the choice is part of every cache key.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum MissingDhPolicy {
    /// Serve the elevation uncorrected.
    #[default]
    Keep,
    /// Drop the pixel (NaN), so lower layers — ultimately the base — show
    /// through.
    Nan,
}

impl MissingDhPolicy {
    pub fn slug(&self) -> &'static str {
        match self {
            Self::Keep => "keep",
            Self::Nan => "nan",
        }
    }
}

impl FromStr for MissingDhPolicy {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.trim().to_ascii_lowercase().as_str() {
            "keep" => Ok(Self::Keep),
            "nan" => Ok(Self::Nan),
            other => Err(format!(
                "unknown heightCorrection.missing `{other}` (valid: keep, nan)"
            )),
        }
    }
}

/// `heightCorrection` of a DEM source in the config JSON.
#[derive(Debug, Clone, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct HeightCorrectionConfig {
    /// URL of the correction product's `manifest.json` (https, gs, s3, r2,
    /// file). The product version is part of the URL, so swapping versions is
    /// a config change.
    pub manifest: String,
    /// [`MissingDhPolicy`]: `keep` (default) or `nan`.
    #[serde(default)]
    pub missing: Option<String>,
}

// ─────────────────────────────── Sampler ───────────────────────────────

// The sampler itself (`sample`, `mesh6_of`, GSI's selection rule) lives in
// `terrain-core`, generic over `NodeGrid`, so the WebAssembly build runs the
// same code; re-exported here so existing paths keep working.
pub use terrain_core::vertical::{DhMemo, DhSelection, NodeGrid, mesh6_of, sample};

/// How a product's grids combine into ΔH: [`DhSelection`] over the fully
/// decoded rasters.
pub type Selection = DhSelection<Arc<Float32Raster>>;

impl NodeGrid for Float32Raster {
    #[inline]
    fn x0(&self) -> f64 {
        self.x0
    }
    #[inline]
    fn y0(&self) -> f64 {
        self.y0
    }
    #[inline]
    fn dx(&self) -> f64 {
        self.dx
    }
    #[inline]
    fn dy(&self) -> f64 {
        self.dy
    }
    #[inline]
    fn width(&self) -> u32 {
        self.width
    }
    #[inline]
    fn height(&self) -> u32 {
        self.height
    }
    #[inline]
    fn get(&self, row: i64, col: i64) -> Option<f64> {
        Float32Raster::get(self, row, col)
    }
}

/// A loaded height-correction product: `H_to = H_from + ΔH`.
pub struct DhProduct {
    pub id: String,
    pub version: String,
    pub from: VerticalDatum,
    pub to: VerticalDatum,
    pub manifest_url: String,
    pub selection: Selection,
}

impl DhProduct {
    /// ΔH (metres) at `(lat, lon)`, NaN where the product has none.
    pub fn sample(&self, lat: f64, lon: f64) -> f64 {
        self.selection.sample(lat, lon)
    }

    /// `<product>@<version>` — the identity that goes into cache keys.
    pub fn key(&self) -> String {
        format!("{}@{}", self.id, self.version)
    }
}

// ─────────────────────────────── Loading ───────────────────────────────

/// File roles of the v1 hyokorev product, whose manifest predates the
/// machine-readable `selection` block (sampler.py `V1_SELECTION`).
const V1_PRIMARY: &str = "dh_bm.tif";
const V1_LISTED: &str = "dh_tr.tif";
const V1_LIST: &str = "tr_meshes.json";

#[derive(Debug, Deserialize)]
struct Manifest {
    kind: String,
    product: String,
    version: String,
    from: String,
    to: String,
    /// Must be `m`: values are added to elevations in metres.
    units: String,
    /// Must be `H_<to> = H_<from> + dH`: the sign the correction is added with.
    sign: String,
    /// Must be `EPSG:6668`: the grids are sampled as JGD2011 geographic degrees.
    crs: String,
    files: HashMap<String, ManifestFile>,
    #[serde(default)]
    selection: Option<ManifestSelection>,
}

#[derive(Debug, Deserialize)]
struct ManifestFile {
    sha256: String,
    bytes: u64,
}

#[derive(Debug, Deserialize)]
struct ManifestSelection {
    kind: String,
    primary: String,
    listed: String,
    fallback: String,
    list: String,
}

#[derive(Debug, Deserialize)]
struct MeshList {
    meshes: Vec<i64>,
}

fn products() -> &'static tokio::sync::Mutex<HashMap<String, Arc<DhProduct>>> {
    static P: OnceLock<tokio::sync::Mutex<HashMap<String, Arc<DhProduct>>>> = OnceLock::new();
    P.get_or_init(Default::default)
}

/// Load (or fetch from the process-wide cache) the product behind
/// `manifest_url`. A product version is immutable once published, so it is
/// downloaded once per process; failures are not cached.
pub async fn load_product(manifest_url: &str) -> Result<Arc<DhProduct>, String> {
    let mut cache = products().lock().await;
    if let Some(p) = cache.get(manifest_url) {
        return Ok(p.clone());
    }
    let p = Arc::new(fetch_product(manifest_url).await?);
    cache.insert(manifest_url.to_string(), p.clone());
    Ok(p)
}

async fn fetch_product(manifest_url: &str) -> Result<DhProduct, String> {
    let base = Url::parse(manifest_url).map_err(|e| format!("manifest URL: {e}"))?;
    let raw = fetch_bytes(&base).await?;
    let m: Manifest =
        serde_json::from_slice(&raw).map_err(|e| format!("{manifest_url}: manifest: {e}"))?;
    if m.kind != "height_correction" {
        return Err(format!(
            "{manifest_url}: kind is `{}`, not `height_correction`",
            m.kind
        ));
    }
    let from: VerticalDatum = m.from.parse()?;
    let to: VerticalDatum = m.to.parse()?;
    if from == to {
        return Err(format!("{manifest_url}: from == to ({from})"));
    }
    // Semantics the sampler relies on. Anything else is refused rather than
    // reinterpreted: centimetres added as metres, a projected grid read as
    // degrees, or a reversed sign would all load and serve wrong heights.
    if m.units != "m" {
        return Err(format!(
            "{manifest_url}: units `{}` (only `m` is supported)",
            m.units
        ));
    }
    let sign = format!("H_{to} = H_{from} + dH");
    if m.sign.trim() != sign {
        return Err(format!(
            "{manifest_url}: sign `{}` (expected `{sign}`)",
            m.sign
        ));
    }
    if m.crs != "EPSG:6668" {
        return Err(format!(
            "{manifest_url}: crs `{}` (only EPSG:6668, JGD2011 geographic, is supported)",
            m.crs
        ));
    }

    // File roles: the manifest's `selection` block; else the v1 layout; else a
    // single-grid product. Anything else is refused rather than guessed.
    enum Roles {
        Listed {
            primary: String,
            listed: String,
            fallback: String,
            list: String,
        },
        Single(String),
    }
    let tifs: Vec<&String> = m.files.keys().filter(|k| k.ends_with(".tif")).collect();
    let roles = match &m.selection {
        Some(s) if s.kind == "listed-meshes" => Roles::Listed {
            primary: s.primary.clone(),
            listed: s.listed.clone(),
            fallback: s.fallback.clone(),
            list: s.list.clone(),
        },
        Some(s) => {
            return Err(format!(
                "{manifest_url}: unsupported selection kind `{}`",
                s.kind
            ));
        }
        None if [V1_PRIMARY, V1_LISTED, V1_LIST]
            .iter()
            .all(|f| m.files.contains_key(*f)) =>
        {
            Roles::Listed {
                primary: V1_PRIMARY.into(),
                listed: V1_LISTED.into(),
                fallback: V1_LISTED.into(),
                list: V1_LIST.into(),
            }
        }
        None if tifs.len() == 1 => Roles::Single(tifs[0].clone()),
        None => {
            return Err(format!(
                "{manifest_url}: no `selection` and not a single-grid product; \
                 cannot tell how its grids combine"
            ));
        }
    };

    let mut grids: HashMap<String, Arc<Float32Raster>> = HashMap::new();
    let grid = |name: String| {
        let base = base.clone();
        let entry = m.files.get(&name).map(|f| (f.sha256.clone(), f.bytes));
        async move {
            let bytes = fetch_verified(&base, &name, entry).await?;
            read_grid(&name, bytes).await.map(Arc::new)
        }
    };
    let selection = match roles {
        Roles::Single(name) => Selection::Single(grid(name).await?),
        Roles::Listed {
            primary,
            listed,
            fallback,
            list,
        } => {
            for name in [&primary, &listed, &fallback] {
                if !grids.contains_key(name) {
                    let g = grid(name.clone()).await?;
                    grids.insert(name.clone(), g);
                }
            }
            let (p, l, f) = (
                grids[&primary].clone(),
                grids[&listed].clone(),
                grids[&fallback].clone(),
            );
            if !p.same_grid(&l) || !p.same_grid(&f) {
                return Err(format!(
                    "{manifest_url}: all grids of a product must share one grid"
                ));
            }
            let entry = m.files.get(&list).map(|f| (f.sha256.clone(), f.bytes));
            let ml: MeshList = serde_json::from_slice(&fetch_verified(&base, &list, entry).await?)
                .map_err(|e| format!("{list}: {e}"))?;
            if ml.meshes.is_empty() || ml.meshes.iter().any(|m| !(100000..=999999).contains(m)) {
                return Err(format!(
                    "{list}: `meshes` must be a non-empty list of 6-digit secondary mesh codes"
                ));
            }
            Selection::ListedMeshes {
                primary: p,
                listed: l,
                fallback: f,
                meshes: ml.meshes.into_iter().collect(),
            }
        }
    };
    let product = DhProduct {
        id: m.product,
        version: m.version,
        from,
        to,
        manifest_url: manifest_url.to_string(),
        selection,
    };
    let resident: usize = match &product.selection {
        Selection::Single(g) => g.resident_bytes(),
        Selection::ListedMeshes {
            primary, listed, ..
        } => primary.resident_bytes() + listed.resident_bytes(),
    };
    tracing::info!(
        product = %product.key(),
        from = %product.from,
        to = %product.to,
        resident_mib = resident as f64 / (1024.0 * 1024.0),
        "Loaded height-correction product"
    );
    Ok(product)
}

/// Fetch `name` next to the manifest and check it against the manifest's
/// size and sha256 — the manifest is the product's definition, so a file it
/// does not list, or that differs from it, is refused.
async fn fetch_verified(
    base: &Url,
    name: &str,
    entry: Option<(String, u64)>,
) -> Result<bytes::Bytes, String> {
    let Some((sha, size)) = entry else {
        return Err(format!("manifest does not list `{name}`"));
    };
    let url = base
        .join(name)
        .map_err(|e| format!("{name}: bad file URL: {e}"))?;
    let bytes = fetch_bytes(&url).await?;
    if bytes.len() as u64 != size {
        return Err(format!(
            "{url}: {} bytes, manifest says {size}",
            bytes.len()
        ));
    }
    let got = Sha256::digest(&bytes)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect::<String>();
    if !got.eq_ignore_ascii_case(&sha) {
        return Err(format!("{url}: sha256 {got}, manifest says {sha}"));
    }
    Ok(bytes)
}

/// GET a whole object through the same object-store backends as the COG
/// overlays (https / gs / s3 / r2), plus `file://` for local copies.
async fn fetch_bytes(url: &Url) -> Result<bytes::Bytes, String> {
    let (store, path): (Arc<dyn ObjectStore>, ObjectPath) = if url.scheme() == "file" {
        let p = url
            .to_file_path()
            .map_err(|_| format!("{url}: not a local path"))?;
        let path = ObjectPath::from_absolute_path(&p).map_err(|e| format!("{url}: {e}"))?;
        (Arc::new(LocalFileSystem::new()), path)
    } else {
        super::cog_dem::build_object_store(url.as_str()).map_err(|e| format!("{url}: {e}"))?
    };
    let res = store.get(&path).await.map_err(|e| format!("{url}: {e}"))?;
    res.bytes().await.map_err(|e| format!("{url}: {e}"))
}

/// Parse a downloaded COG with the regular [`CogReader`] (over an in-memory
/// object store) and keep its full-resolution image.
async fn read_grid(name: &str, bytes: bytes::Bytes) -> Result<Float32Raster, String> {
    let store = Arc::new(InMemory::new());
    let path = ObjectPath::from(name);
    store
        .put(&path, bytes.into())
        .await
        .map_err(|e| format!("{name}: {e}"))?;
    let reader = CogReader::open(store, path)
        .await
        .map_err(|e| format!("{name}: {e}"))?;
    // The sampler works in longitude / latitude degrees.
    if reader.crs() != crate::cog::CogCrs::Geographic {
        return Err(format!("{name}: not a geographic (degree) grid"));
    }
    reader
        .read_full_resolution_f32()
        .await
        .map_err(|e| format!("{name}: {e}"))
}

// ─────────────────────────────── Planning ───────────────────────────────

/// Datum declarations of one DEM source, as read from the config JSON.
#[derive(Debug, Default)]
pub struct SourceDeclaration<'a> {
    /// Source-level `verticalDatum` (default for every layer).
    pub default_datum: Option<&'a str>,
    /// Per built overlay (bottom → top): the layer's own `verticalDatum`.
    pub layer_datums: Vec<Option<&'a str>>,
    /// Source-level `heightCorrection`, unparsed.
    pub correction: Option<&'a serde_json::Value>,
}

impl SourceDeclaration<'_> {
    fn is_empty(&self) -> bool {
        self.default_datum.is_none()
            && self.layer_datums.iter().all(Option::is_none)
            && self.correction.is_none()
    }
}

/// What [`plan_source`] decided for a source.
#[derive(Debug, PartialEq)]
pub enum DatumPlan {
    /// Nothing declared: build the source exactly as before.
    Legacy,
    /// Datums declared and consistent; correct the flagged members.
    Checked {
        target: VerticalDatum,
        /// The datum ΔH must convert *from* (the one that is not the target),
        /// when anything needs correcting.
        from: Option<VerticalDatum>,
        base_corrected: bool,
        layer_corrected: Vec<bool>,
        /// `(manifest URL, policy)`, set only when something is corrected.
        correction: Option<(String, MissingDhPolicy)>,
    },
}

/// Check a source's datum declarations against its geoid and the base, and
/// decide which members get ΔH. Any combination that cannot be served
/// correctly is an `Err` naming the reason; the caller refuses the source.
pub fn plan_source(
    geoid: GeoidModel,
    decl: &SourceDeclaration<'_>,
    base: BaseDatum,
) -> Result<DatumPlan, String> {
    if decl.is_empty() {
        return Ok(DatumPlan::Legacy);
    }
    let target = geoid.target_datum().ok_or_else(|| {
        format!(
            "geoid `{geoid}` is not bound to an orthometric datum (only gsigeo2011 → jgd2011 \
             and jpgeo2024-hrefconv → jgd2024 are), so this source cannot declare \
             verticalDatum / heightCorrection"
        )
    })?;
    let default: Option<VerticalDatum> = decl
        .default_datum
        .map(str::parse)
        .transpose()
        .map_err(|e| format!("verticalDatum: {e}"))?;
    let mut layers = Vec::with_capacity(decl.layer_datums.len());
    for (i, d) in decl.layer_datums.iter().enumerate() {
        let d = match d {
            Some(s) => s
                .parse()
                .map_err(|e| format!("layers[{i}].verticalDatum: {e}"))?,
            None => default.ok_or_else(|| {
                format!(
                    "layers[{i}] has no vertical datum (set verticalDatum on the source or the layer)"
                )
            })?,
        };
        layers.push(d);
    }
    let correction: Option<(HeightCorrectionConfig, MissingDhPolicy)> = match decl.correction {
        None => None,
        Some(v) => {
            let c: HeightCorrectionConfig =
                serde_json::from_value(v.clone()).map_err(|e| format!("heightCorrection: {e}"))?;
            let policy = c
                .missing
                .as_deref()
                .map(str::parse)
                .transpose()?
                .unwrap_or_default();
            Some((c, policy))
        }
    };

    let base_corrected = match base {
        BaseDatum::Agnostic => false,
        BaseDatum::Known(d) => d != target,
        BaseDatum::Unknown if correction.is_some() => {
            return Err(
                "the base DEM's vertical datum is unknown: set DEM_VERTICAL_DATUM (jgd2011 | \
                 jgd2024) for the DEM_URL upstream, or use DEM_URL=sealevel, before a source \
                 can apply a height correction"
                    .to_string(),
            );
        }
        BaseDatum::Unknown => {
            tracing::warn!(
                "a DEM source declares vertical datums on a base of unknown datum \
                 (DEM_VERTICAL_DATUM unset); base pixels are served as-is"
            );
            false
        }
    };
    let layer_corrected: Vec<bool> = layers.iter().map(|d| *d != target).collect();
    let needs = base_corrected || layer_corrected.iter().any(|&c| c);
    if !needs {
        if correction.is_some() {
            tracing::warn!(
                "heightCorrection configured but every layer is already {target}; it is not applied"
            );
        }
        return Ok(DatumPlan::Checked {
            target,
            from: None,
            base_corrected,
            layer_corrected,
            correction: None,
        });
    }
    // Only two datums exist, so everything to correct is in the other one.
    let from = match target {
        VerticalDatum::Jgd2011 => VerticalDatum::Jgd2024,
        VerticalDatum::Jgd2024 => VerticalDatum::Jgd2011,
    };
    let Some((c, policy)) = correction else {
        let what: Vec<String> = base_corrected
            .then(|| "the base DEM".to_string())
            .into_iter()
            .chain(
                layer_corrected
                    .iter()
                    .enumerate()
                    .filter(|(_, c)| **c)
                    .map(|(i, _)| format!("layers[{i}]")),
            )
            .collect();
        return Err(format!(
            "{} {} {from} but the geoid `{geoid}` expects {target}, and no heightCorrection is \
             configured",
            what.join(", "),
            if what.len() == 1 { "is" } else { "are" },
        ));
    };
    Ok(DatumPlan::Checked {
        target,
        from: Some(from),
        base_corrected,
        layer_corrected,
        correction: Some((c.manifest, policy)),
    })
}

/// Check that a loaded product converts exactly `from → target`.
pub fn check_product(
    product: &DhProduct,
    from: VerticalDatum,
    target: VerticalDatum,
) -> Result<(), String> {
    if product.from == from && product.to == target {
        return Ok(());
    }
    if product.from == target && product.to == from {
        return Err(format!(
            "{} converts {} → {}, but this source needs {from} → {target} (no inverse \
             correction is available)",
            product.key(),
            product.from,
            product.to
        ));
    }
    Err(format!(
        "{} converts {} → {}, but this source needs {from} → {target}",
        product.key(),
        product.from,
        product.to
    ))
}

// ─────────────────────────────── Applying ───────────────────────────────

/// The correction a composite DEM applies: which members, with which product.
pub struct SourceCorrection {
    pub product: Arc<DhProduct>,
    pub policy: MissingDhPolicy,
    pub base: bool,
    /// Per overlay, in composite order.
    pub layers: Vec<bool>,
    descriptor: String,
}

impl SourceCorrection {
    pub fn new(
        product: Arc<DhProduct>,
        policy: MissingDhPolicy,
        base: bool,
        base_datum: BaseDatum,
        layers: Vec<bool>,
    ) -> Self {
        let mask: String = layers.iter().map(|&c| if c { '1' } else { '0' }).collect();
        let descriptor = format!(
            "vcorr={key}:{from}-to-{to}:missing={policy}:base={base_datum}:base-dh={base_flag}:layers={mask:x}",
            key = product.key(),
            from = product.from,
            to = product.to,
            policy = policy.slug(),
            base_datum = base_datum.slug(),
            base_flag = if base { "yes" } else { "no" },
            mask = xxh64(mask.as_bytes(), 0),
        );
        Self {
            product,
            policy,
            base,
            layers,
            descriptor,
        }
    }

    /// Cache-key / ETag fragment: product id + version, the missing-ΔH
    /// policy, and which members are corrected. Only sources that apply a
    /// correction carry it, so every other source keeps its keys.
    pub fn descriptor(&self) -> &str {
        &self.descriptor
    }

    /// Add ΔH to every finite elevation of `tile`, which was evaluated for
    /// tile `z/x/y` (the zoom the member was actually asked for).
    pub fn apply(
        &self,
        tile: &mut DemTile,
        z: u8,
        x: u32,
        y: u32,
        tile_size: u32,
        memo: &mut DhMemo,
    ) {
        let positions = tile
            .positions
            .unwrap_or_else(|| PixelPositions::centres(tile_size));
        let grid = memo.grid(positions, z, x, y, tile_size);
        let n = tile_size as usize;
        for (idx, v) in tile.elevations.iter_mut().enumerate() {
            if !v.is_finite() {
                continue;
            }
            let dh = grid.get(&self.product.selection, idx % n, idx / n);
            if dh.is_finite() {
                *v += dh;
            } else if self.policy == MissingDhPolicy::Nan {
                *v = f64::NAN;
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_dir() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("fixtures/vertical/hyokorev-jgd2011-to-jgd2024/v1")
    }

    fn fixture_manifest_url() -> String {
        Url::from_file_path(fixture_dir().join("manifest.json"))
            .unwrap()
            .to_string()
    }

    #[derive(Deserialize)]
    struct Golden {
        product: HashMap<String, String>,
        vectors: Vec<GoldenVector>,
    }

    #[derive(Deserialize)]
    struct GoldenVector {
        label: String,
        lon_hex: String,
        lat_hex: String,
        mesh6: i64,
        dh_hex: Option<String>,
    }

    /// Parse Python's `float.hex()` (`[-]0x1.<hex>p<exp>`, or `0x0.0p+0`).
    fn parse_hex_float(s: &str) -> f64 {
        let (neg, s) = s.strip_prefix('-').map_or((false, s), |r| (true, r));
        let s = s.strip_prefix("0x").expect("0x prefix");
        let (mant, exp) = s.split_once('p').expect("p exponent");
        let (int, frac) = mant.split_once('.').unwrap_or((mant, ""));
        let mut v = u64::from_str_radix(int, 16).unwrap() as f64;
        let mut scale = 1.0 / 16.0;
        for c in frac.chars() {
            v += c.to_digit(16).unwrap() as f64 * scale;
            scale /= 16.0;
        }
        let v = v * 2f64.powi(exp.parse::<i32>().unwrap());
        if neg { -v } else { v }
    }

    #[test]
    fn hex_float_parser_is_exact() {
        assert_eq!(parse_hex_float("0x0.0p+0"), 0.0);
        assert_eq!(parse_hex_float("0x1.0640000000000p+7"), 131.125);
        assert_eq!(parse_hex_float("0x1.f89108334ec72p+4"), 31.535408211155705);
        assert_eq!(
            parse_hex_float("-0x1.0354dc69d6a27p-3"),
            -0.1266267032431909
        );
    }

    /// The Rust sampler must reproduce `sampler.DhGsi` on the published v1
    /// product: same NaN set, same selection (mesh6), same values.
    #[tokio::test]
    async fn golden_vectors_match_reference_sampler() {
        let golden: Golden = serde_json::from_slice(
            &std::fs::read(
                fixture_dir()
                    .parent()
                    .unwrap()
                    .parent()
                    .unwrap()
                    .join("hyokorev-jgd2011-to-jgd2024-v1.golden.json"),
            )
            .unwrap(),
        )
        .unwrap();
        // The vectors were generated from exactly these files.
        for (name, sha) in &golden.product {
            let bytes = std::fs::read(fixture_dir().join(name)).unwrap();
            let got: String = Sha256::digest(&bytes)
                .iter()
                .map(|b| format!("{b:02x}"))
                .collect();
            assert_eq!(&got, sha, "{name}");
        }

        let product = fetch_product(&fixture_manifest_url()).await.unwrap();
        assert_eq!(product.key(), "hyokorev-jgd2011-to-jgd2024@v1");
        assert_eq!(
            (product.from, product.to),
            (VerticalDatum::Jgd2011, VerticalDatum::Jgd2024)
        );

        let mut max_abs = 0.0f64;
        let mut bit_exact = 0usize;
        let mut by_label: HashMap<&str, usize> = HashMap::new();
        for v in &golden.vectors {
            let lon = parse_hex_float(&v.lon_hex);
            let lat = parse_hex_float(&v.lat_hex);
            assert_eq!(mesh6_of(lat, lon), v.mesh6, "{} {lon} {lat}", v.label);
            let got = product.sample(lat, lon);
            match &v.dh_hex {
                None => assert!(
                    got.is_nan(),
                    "{}: expected NaN at {lon},{lat}, got {got}",
                    v.label
                ),
                Some(h) => {
                    // The contract is bit identity with the reference, not
                    // a tolerance: same operations, same order, in f64.
                    let want = parse_hex_float(h);
                    assert_eq!(
                        got.to_bits(),
                        want.to_bits(),
                        "{}: {lon},{lat}: got {got:e}, want {want:e}",
                        v.label
                    );
                    max_abs = max_abs.max((got - want).abs());
                    bit_exact += 1;
                }
            }
            *by_label.entry(v.label.as_str()).or_default() += 1;
        }
        let finite = golden.vectors.iter().filter(|v| v.dh_hex.is_some()).count();
        eprintln!(
            "golden: {} vectors ({} finite, {} NaN), max |Δ| = {max_abs:e} m, bit-exact {bit_exact}/{finite}",
            golden.vectors.len(),
            finite,
            golden.vectors.len() - finite
        );
        // Every category of the fixture was exercised.
        for label in [
            "listed-473121",
            "bm-gap-48310309",
            "boundary-473120-west",
            "boundary-473121-east",
            "boundary-exact-lon",
            "boundary-exact-corner",
            "noparam-northern-territories",
            "noparam-iwoto",
            "noparam-senkaku",
            "noparam-nanatsujima",
            "random-extent",
            "random-near-node",
        ] {
            assert!(by_label.get(label).copied().unwrap_or(0) > 0, "{label}");
        }
        assert!(finite > 2000);
    }

    // ── Golden nodes: the v1 nodes the golden points read ──
    //
    // `terrain-core` re-runs the golden vectors over a `SparseGrid` holding
    // only these nodes (natively and in wasm32), without a COG reader.

    const GOLDEN_NODES: &str = "hyokorev-jgd2011-to-jgd2024-v1.golden-nodes.json";

    fn golden_dir() -> std::path::PathBuf {
        fixture_dir()
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .to_path_buf()
    }

    /// A [`NodeGrid`] that records every node `sample` reads.
    struct Recording<'a> {
        inner: &'a Float32Raster,
        seen: std::cell::RefCell<std::collections::BTreeMap<(i64, i64), Option<f64>>>,
    }

    impl NodeGrid for Recording<'_> {
        fn x0(&self) -> f64 {
            self.inner.x0
        }
        fn y0(&self) -> f64 {
            self.inner.y0
        }
        fn dx(&self) -> f64 {
            self.inner.dx
        }
        fn dy(&self) -> f64 {
            self.inner.dy
        }
        fn width(&self) -> u32 {
            self.inner.width
        }
        fn height(&self) -> u32 {
            self.inner.height
        }
        fn get(&self, row: i64, col: i64) -> Option<f64> {
            let v = self.inner.get(row, col);
            self.seen.borrow_mut().insert((row, col), v);
            v
        }
    }

    /// The golden-nodes fixture, generated from the v1 product files: the
    /// grid georeference, the selection roles, the TR mesh list, and every
    /// node (value, or `null` = nodata / outside) that sampling the 3,978
    /// golden points reads, as exact hex floats.
    async fn golden_nodes_json() -> String {
        use terrain_core::hexfloat::format as hex;

        let golden: Golden = serde_json::from_slice(
            &std::fs::read(golden_dir().join("hyokorev-jgd2011-to-jgd2024-v1.golden.json"))
                .unwrap(),
        )
        .unwrap();
        let product = fetch_product(&fixture_manifest_url()).await.unwrap();
        let Selection::ListedMeshes {
            primary,
            listed,
            fallback,
            meshes,
        } = &product.selection
        else {
            panic!("v1 is a listed-meshes product");
        };
        assert!(Arc::ptr_eq(listed, fallback), "v1: listed == fallback");
        let bm = Recording {
            inner: primary,
            seen: Default::default(),
        };
        let tr = Recording {
            inner: listed,
            seen: Default::default(),
        };
        let recording = DhSelection::ListedMeshes {
            primary: &bm,
            listed: &tr,
            fallback: &tr,
            meshes: meshes.clone(),
        };
        for v in &golden.vectors {
            let lon = parse_hex_float(&v.lon_hex);
            let lat = parse_hex_float(&v.lat_hex);
            let got = recording.sample(lat, lon);
            assert_eq!(got.to_bits(), product.sample(lat, lon).to_bits());
        }

        let mut out = String::new();
        out.push_str("{\n");
        out.push_str(
            "  \"generator\": \"tile/src/terrain/vertical.rs bless_golden_nodes \
             (cargo test -p tile --lib -- --ignored bless_golden_nodes)\",\n",
        );
        out.push_str("  \"golden\": \"hyokorev-jgd2011-to-jgd2024-v1.golden.json\",\n");
        let mut files: Vec<_> = golden.product.iter().collect();
        files.sort();
        out.push_str("  \"product\": {\n");
        for (k, (name, sha)) in files.iter().enumerate() {
            let comma = if k + 1 < files.len() { "," } else { "" };
            out.push_str(&format!("    \"{name}\": \"{sha}\"{comma}\n"));
        }
        out.push_str("  },\n");
        out.push_str(
            "  \"selection\": {\"kind\": \"listed-meshes\", \"primary\": \"dh_bm.tif\", \
             \"listed\": \"dh_tr.tif\", \"fallback\": \"dh_tr.tif\"},\n",
        );
        let mut list: Vec<i64> = meshes.iter().copied().collect();
        list.sort();
        let list: Vec<String> = list.iter().map(i64::to_string).collect();
        out.push_str(&format!("  \"tr_meshes\": [{}],\n", list.join(", ")));
        out.push_str("  \"grids\": {\n");
        for (k, (name, rec)) in [("dh_bm.tif", &bm), ("dh_tr.tif", &tr)]
            .into_iter()
            .enumerate()
        {
            let g = rec.inner;
            out.push_str(&format!("    \"{name}\": {{\n"));
            out.push_str(&format!(
                "      \"width\": {}, \"height\": {}, \"x0\": \"{}\", \"y0\": \"{}\", \"dx\": \"{}\", \"dy\": \"{}\",\n",
                g.width,
                g.height,
                hex(g.x0),
                hex(g.y0),
                hex(g.dx),
                hex(g.dy)
            ));
            out.push_str("      \"nodes\": [\n");
            let seen = rec.seen.borrow();
            for (n, ((row, col), v)) in seen.iter().enumerate() {
                let v = v.map_or("null".to_string(), |v| format!("\"{}\"", hex(v)));
                let comma = if n + 1 < seen.len() { "," } else { "" };
                out.push_str(&format!("        [{row}, {col}, {v}]{comma}\n"));
            }
            out.push_str("      ]\n");
            out.push_str(if k == 0 { "    },\n" } else { "    }\n" });
        }
        out.push_str("  }\n}\n");
        out
    }

    /// Regenerate the golden-nodes fixture:
    /// `cargo test -p tile --lib -- --ignored bless_golden_nodes`.
    #[tokio::test]
    #[ignore = "writes tile/fixtures/vertical/*.golden-nodes.json"]
    async fn bless_golden_nodes() {
        let json = golden_nodes_json().await;
        std::fs::write(golden_dir().join(GOLDEN_NODES), json).unwrap();
    }

    /// The committed golden-nodes fixture is exactly what the v1 product
    /// files give (so the WebAssembly golden test reads real nodes).
    #[tokio::test]
    async fn golden_nodes_fixture_is_current() {
        let want = golden_nodes_json().await;
        let got = std::fs::read_to_string(golden_dir().join(GOLDEN_NODES)).unwrap();
        assert!(
            got == want,
            "{GOLDEN_NODES} is stale: cargo test -p tile --lib -- --ignored bless_golden_nodes"
        );
    }

    /// The v1 manifest has no `selection` block; it must resolve to GSI's
    /// rule over dh_bm / dh_tr / tr_meshes.json, not to one grid.
    #[tokio::test]
    async fn v1_manifest_resolves_to_listed_mesh_rule() {
        let p = fetch_product(&fixture_manifest_url()).await.unwrap();
        match &p.selection {
            Selection::ListedMeshes {
                meshes,
                listed,
                fallback,
                ..
            } => {
                assert_eq!(meshes.len(), 22);
                assert!(meshes.contains(&473121) && !meshes.contains(&483103));
                assert!(Arc::ptr_eq(listed, fallback));
            }
            Selection::Single(_) => panic!("v1 must not be read as a single grid"),
        }
        // Listed mesh 473121 is TR, its western neighbour 473120 is BM: the
        // two sides of lon 131.125 come from different grids, and a point on
        // the boundary belongs to the east (TR) side.
        let Selection::ListedMeshes {
            primary, listed, ..
        } = &p.selection
        else {
            unreachable!()
        };
        let lat = 31.54;
        let (e, w) = (131.125 + 1e-9, 131.125 - 1e-9);
        assert_eq!(p.sample(lat, e), sample(listed, lat, e));
        assert_eq!(p.sample(lat, w), sample(primary, lat, w));
        assert_eq!(p.sample(lat, 131.125), sample(listed, lat, 131.125));
        assert_ne!(sample(listed, lat, 131.125), sample(primary, lat, 131.125));
    }

    #[tokio::test]
    async fn tampered_file_is_refused() {
        let dir = tempfile::tempdir().unwrap();
        for f in ["manifest.json", "dh_bm.tif", "dh_tr.tif", "tr_meshes.json"] {
            std::fs::copy(fixture_dir().join(f), dir.path().join(f)).unwrap();
        }
        let mut list = std::fs::read(dir.path().join("tr_meshes.json")).unwrap();
        list.push(b'\n');
        std::fs::write(dir.path().join("tr_meshes.json"), list).unwrap();
        let url = Url::from_file_path(dir.path().join("manifest.json")).unwrap();
        let err = fetch_product(url.as_str()).await.err().unwrap();
        assert!(err.contains("tr_meshes.json"), "{err}");
    }

    /// Manifest semantics the sampler relies on are checked, not assumed.
    #[tokio::test]
    async fn manifest_semantics_are_enforced() {
        for (field, value) in [
            ("units", "cm"),
            ("crs", "EPSG:3857"),
            ("sign", "H_jgd2011 = H_jgd2024 + dH"),
        ] {
            let dir = tempfile::tempdir().unwrap();
            for f in ["dh_bm.tif", "dh_tr.tif", "tr_meshes.json"] {
                std::fs::copy(fixture_dir().join(f), dir.path().join(f)).unwrap();
            }
            let mut m: serde_json::Value = serde_json::from_slice(
                &std::fs::read(fixture_dir().join("manifest.json")).unwrap(),
            )
            .unwrap();
            m[field] = serde_json::Value::String(value.into());
            std::fs::write(dir.path().join("manifest.json"), m.to_string()).unwrap();
            let url = Url::from_file_path(dir.path().join("manifest.json")).unwrap();
            let err = fetch_product(url.as_str()).await.err().unwrap();
            assert!(err.contains(field), "{field}: {err}");
        }
    }

    /// A numeric GDAL_NODATA sentinel (not just NaN) comes back as no value,
    /// so it can never be added to terrain as a ΔH. Uses the -9999 fixture.
    #[tokio::test]
    async fn numeric_nodata_is_honoured_by_full_resolution_reader() {
        let bytes = std::fs::read(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures/dem_nodata.tif"),
        )
        .unwrap();
        let r = read_grid("dem_nodata.tif", bytes.into()).await.unwrap();
        // Column 0 holds data, columns 128.. are -9999 in the file.
        assert!(r.get(0, 0).is_some());
        assert_eq!(r.get(0, 200), None);
        assert_eq!(r.get(255, 255), None);
    }

    fn decl<'a>(
        default: Option<&'a str>,
        layers: Vec<Option<&'a str>>,
        corr: Option<&'a serde_json::Value>,
    ) -> SourceDeclaration<'a> {
        SourceDeclaration {
            default_datum: default,
            layer_datums: layers,
            correction: corr,
        }
    }

    #[test]
    fn nothing_declared_is_legacy() {
        let d = decl(None, vec![None, None], None);
        for base in [BaseDatum::Unknown, BaseDatum::Agnostic] {
            for g in GeoidModel::all() {
                assert_eq!(plan_source(*g, &d, base).unwrap(), DatumPlan::Legacy);
            }
        }
    }

    #[test]
    fn jgd2011_stack_under_jgd2024_geoid_is_corrected() {
        let c = serde_json::json!({"manifest": "https://x/v1/manifest.json"});
        let d = decl(Some("jgd2011"), vec![None, Some("jgd2024"), None], Some(&c));
        let plan = plan_source(GeoidModel::Jpgeo2024Hrefconv, &d, BaseDatum::Agnostic).unwrap();
        assert_eq!(
            plan,
            DatumPlan::Checked {
                target: VerticalDatum::Jgd2024,
                from: Some(VerticalDatum::Jgd2011),
                base_corrected: false,
                layer_corrected: vec![true, false, true],
                correction: Some(("https://x/v1/manifest.json".into(), MissingDhPolicy::Keep)),
            }
        );
        // A declared jgd2011 base is corrected too; the sea-level base never is.
        let plan = plan_source(
            GeoidModel::Jpgeo2024Hrefconv,
            &d,
            BaseDatum::Known(VerticalDatum::Jgd2011),
        )
        .unwrap();
        assert!(matches!(
            plan,
            DatumPlan::Checked {
                base_corrected: true,
                ..
            }
        ));
    }

    #[test]
    fn refused_combinations() {
        let c = serde_json::json!({"manifest": "https://x/v1/manifest.json"});
        // jgd2011 layers, jgd2024 geoid, no correction.
        assert!(
            plan_source(
                GeoidModel::Jpgeo2024Hrefconv,
                &decl(Some("jgd2011"), vec![None], None),
                BaseDatum::Agnostic
            )
            .is_err()
        );
        // JPGEO2024 alone has no datum.
        assert!(
            plan_source(
                GeoidModel::Jpgeo2024,
                &decl(Some("jgd2024"), vec![None], None),
                BaseDatum::Agnostic
            )
            .is_err()
        );
        // A correction on a base of unknown datum.
        assert!(
            plan_source(
                GeoidModel::Jpgeo2024Hrefconv,
                &decl(Some("jgd2011"), vec![None], Some(&c)),
                BaseDatum::Unknown
            )
            .is_err()
        );
        // A layer without any datum once datums are declared.
        assert!(
            plan_source(
                GeoidModel::Gsigeo2011,
                &decl(None, vec![Some("jgd2011"), None], None),
                BaseDatum::Agnostic
            )
            .is_err()
        );
        // Typos are refused, not ignored.
        assert!(
            plan_source(
                GeoidModel::Gsigeo2011,
                &decl(Some("jgd2O11"), vec![None], None),
                BaseDatum::Agnostic
            )
            .is_err()
        );
        let bad = serde_json::json!({"manifest": "https://x", "missing": "zero"});
        assert!(
            plan_source(
                GeoidModel::Jpgeo2024Hrefconv,
                &decl(Some("jgd2011"), vec![None], Some(&bad)),
                BaseDatum::Agnostic
            )
            .is_err()
        );
    }

    #[tokio::test]
    async fn inverse_correction_is_refused() {
        // A jgd2024 layer in a jgd2011 source needs 2024 → 2011; v1 is 2011 → 2024.
        let c = serde_json::json!({"manifest": fixture_manifest_url()});
        let plan = plan_source(
            GeoidModel::Gsigeo2011,
            &decl(Some("jgd2024"), vec![None], Some(&c)),
            BaseDatum::Agnostic,
        )
        .unwrap();
        let DatumPlan::Checked {
            target,
            from: Some(from),
            ..
        } = plan
        else {
            panic!("{plan:?}")
        };
        let product = load_product(&fixture_manifest_url()).await.unwrap();
        let err = check_product(&product, from, target).unwrap_err();
        assert!(err.contains("no inverse"), "{err}");
        check_product(&product, VerticalDatum::Jgd2011, VerticalDatum::Jgd2024).unwrap();
    }

    #[tokio::test]
    async fn apply_adds_dh_and_honours_missing_policy() {
        let product = load_product(&fixture_manifest_url()).await.unwrap();
        // z14 tile over Miyazaki (land, inside the grids) and one over the
        // open Pacific (no ΔH).
        for (z, x, y, expect_dh) in [(14u8, 14163u32, 6677u32, true), (10, 924, 422, false)] {
            let n = 8u32;
            for policy in [MissingDhPolicy::Keep, MissingDhPolicy::Nan] {
                let corr = SourceCorrection::new(
                    product.clone(),
                    policy,
                    false,
                    BaseDatum::Agnostic,
                    vec![true],
                );
                let mut tile = DemTile {
                    elevations: vec![100.0; (n * n) as usize],
                    etag: None,
                    positions: None,
                };
                tile.elevations[0] = f64::NAN;
                corr.apply(&mut tile, z, x, y, n, &mut DhMemo::default());
                assert!(tile.elevations[0].is_nan(), "nodata stays nodata");
                let p = PixelPositions::centres(n);
                for j in 0..n {
                    for i in 0..n {
                        if (i, j) == (0, 0) {
                            continue;
                        }
                        let (lon, lat) = p.lonlat(z, x, y, i, j);
                        let dh = product.sample(lat, lon);
                        let v = tile.elevations[(j * n + i) as usize];
                        assert_eq!(dh.is_finite(), expect_dh);
                        match (dh.is_finite(), policy) {
                            (true, _) => assert_eq!(v, 100.0 + dh),
                            (false, MissingDhPolicy::Keep) => assert_eq!(v, 100.0),
                            (false, MissingDhPolicy::Nan) => assert!(v.is_nan()),
                        }
                    }
                }
            }
        }
    }

    #[test]
    fn sea_level_base_is_agnostic_whatever_is_declared() {
        assert_eq!(
            BaseDatum::resolve(true, Some("jgd2011")),
            BaseDatum::Agnostic
        );
        assert_eq!(BaseDatum::resolve(true, None), BaseDatum::Agnostic);
        assert_eq!(BaseDatum::resolve(false, None), BaseDatum::Unknown);
        assert_eq!(
            BaseDatum::resolve(false, Some("JGD2011")),
            BaseDatum::Known(VerticalDatum::Jgd2011)
        );
        assert_eq!(BaseDatum::resolve(false, Some("2011")), BaseDatum::Unknown);
    }
}
