//! Embeds two vendored sets of files, one `(name, content)` entry per file.
//!
//! * `CODELISTS_4_0` holds the published i-UR 4.0 code lists in
//!   `../fixtures/codelists/4.0/`, named by file name. Only that one minor is
//!   embedded; a sibling minor vendored for reference is ignored.
//! * `OGC_SCHEMAS` holds every `.xsd` under `../fixtures/schemas/ogc/`, named
//!   by its `/`-separated path relative to that directory.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let fixtures = manifest.join("..").join("fixtures");

    let codelists = fixtures.join("codelists").join("4.0");
    let mut entries: Vec<(String, PathBuf)> = fs::read_dir(&codelists)
        .unwrap_or_else(|e| panic!("{}: {e}", codelists.display()))
        .filter_map(|entry| entry.ok())
        .filter(|entry| entry.file_type().is_ok_and(|t| t.is_file()))
        .map(|entry| (entry.file_name().into_string().unwrap(), entry.path()))
        .filter(|(name, _)| name.ends_with(".xml"))
        .collect();
    entries.sort();
    write_table(
        &codelists,
        &entries,
        "The published i-UR 4.0 code lists vendored in `fixtures/codelists/4.0/`,\n\
         /// generated by `build.rs`. One `(file name, content)` per list.",
        "CODELISTS_4_0",
        "codelists_gen.rs",
    );

    let ogc = fixtures.join("schemas").join("ogc");
    let mut entries = Vec::new();
    collect_xsd(&ogc, &ogc, &mut entries);
    entries.sort();
    write_table(
        &ogc,
        &entries,
        "The OGC CityGML 3.0 schemas vendored in `fixtures/schemas/ogc/`, with the\n\
         /// GML 3.2 documents declaring the base types every feature extends,\n\
         /// generated by `build.rs`. One `(relative path, content)` per schema.",
        "OGC_SCHEMAS",
        "ogc_schemas_gen.rs",
    );
}

fn collect_xsd(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    println!("cargo:rerun-if-changed={}", dir.display());
    for entry in fs::read_dir(dir).unwrap_or_else(|e| panic!("{}: {e}", dir.display())) {
        let path = entry.unwrap().path();
        if path.is_dir() {
            collect_xsd(root, &path, out);
        } else if path.extension().is_some_and(|ext| ext == "xsd") {
            let relative = path
                .strip_prefix(root)
                .unwrap()
                .components()
                .map(|c| c.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/");
            out.push((relative, path));
        }
    }
}

fn write_table(dir: &Path, entries: &[(String, PathBuf)], doc: &str, name: &str, file: &str) {
    println!("cargo:rerun-if-changed={}", dir.display());
    let mut out = String::new();
    writeln!(out, "/// {doc}").unwrap();
    writeln!(out, "pub static {name}: &[(&str, &str)] = &[").unwrap();
    for (key, path) in entries {
        println!("cargo:rerun-if-changed={}", path.display());
        writeln!(out, "    ({key:?}, include_str!({:?})),", path.display()).unwrap();
    }
    writeln!(out, "];").unwrap();

    let target = PathBuf::from(env::var("OUT_DIR").unwrap()).join(file);
    fs::write(&target, out).unwrap_or_else(|e| panic!("{}: {e}", target.display()));
}
