//! Embeds the vendored published i-UR 4.0 code lists (`../fixtures/codelists/`) as
//! `CODELISTS_4_0`, one `(file name, content)` entry per list. A generated
//! include beats 315 hand-written `include_str!` lines and cannot drift from
//! the directory.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let dir = manifest.join("..").join("fixtures").join("codelists");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut names: Vec<String> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("{}: {e}", dir.display()))
        .filter_map(|entry| entry.ok())
        .filter(|entry| entry.file_type().is_ok_and(|t| t.is_file()))
        .map(|entry| entry.file_name().into_string().unwrap())
        .filter(|name| name.ends_with(".xml"))
        .collect();
    names.sort();

    let mut out = String::new();
    writeln!(
        out,
        "/// The published i-UR 4.0 code lists vendored in `fixtures/codelists/`,\n\
         /// generated by `build.rs`. One `(file name, content)` per list."
    )
    .unwrap();
    writeln!(out, "pub static CODELISTS_4_0: &[(&str, &str)] = &[").unwrap();
    for name in &names {
        let path = dir.join(name);
        println!("cargo:rerun-if-changed={}", path.display());
        writeln!(out, "    ({name:?}, include_str!({:?})),", path.display()).unwrap();
    }
    writeln!(out, "];").unwrap();

    let target = PathBuf::from(env::var("OUT_DIR").unwrap()).join("codelists_gen.rs");
    fs::write(&target, out).unwrap_or_else(|e| panic!("{}: {e}", target.display()));
}
