package geocoding

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"strings"
)

// Areas is the resolver for the areas field.
func (r *queryResolver) Areas(ctx context.Context, longitude float64, latitude float64, includeRadii bool) (*Areas, error) {
	// Fetch from GSI API
	result, err := r.gsiClient.Fetch(ctx, longitude, latitude)
	if err != nil {
		// Check for context cancellation
		if ctx.Err() != nil {
			return nil, nil
		}
		return nil, err
	}

	if result == nil || result.MunicipalityCode == "" {
		return nil, nil
	}

	// Build areas from municipality code
	areas, err := BuildAreas(result.MunicipalityCode, includeRadii)
	if err != nil {
		return nil, err
	}

	// Convert full-width space to half-width (same as geo service)
	address := strings.ReplaceAll(result.Name, "\u3000", " ")

	return &Areas{
		Address: address,
		Areas:   areas,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
