//! The ΔH sampler of the vertical-datum height correction.
//!
//! [`sample`] and [`DhSelection::sample`] are a line-by-line port of the
//! normative reference `tile/scripts/vertical-cogs/sampler.py` (`sample`,
//! `mesh6_of`, `DhGsi`); golden tests pin them to vectors generated by it,
//! natively and in WebAssembly.
//!
//! The sampler is generic over [`NodeGrid`], so the same code runs over a
//! fully decoded raster (the server), lazily decoded blocks (the Worker), or
//! a sparse set of nodes (the golden-nodes fixture).

use std::collections::{HashMap, HashSet};
use std::rc::Rc;
use std::sync::Arc;

use crate::positions::PixelPositions;

/// A node-centred raster the ΔH sampler can read: pixel `(row, col)` covers
/// `[x0 + col·dx, x0 + (col+1)·dx] × [y0 − (row+1)·dy, y0 − row·dy]` and its
/// value lives at the pixel centre.
pub trait NodeGrid {
    /// Longitude (x) of the outer west edge of column 0.
    fn x0(&self) -> f64;
    /// Latitude (y) of the outer north edge of row 0.
    fn y0(&self) -> f64;
    /// Pixel width, > 0.
    fn dx(&self) -> f64;
    /// Pixel height, > 0 (rows run north → south).
    fn dy(&self) -> f64;
    fn width(&self) -> u32;
    fn height(&self) -> u32;
    /// Value at `(row, col)`, or `None` when it is outside the grid or
    /// nodata. Must accept any `i64` without panicking.
    fn get(&self, row: i64, col: i64) -> Option<f64>;
}

macro_rules! forward_node_grid {
    ($($ptr:ty),*) => {$(
        impl<G: NodeGrid + ?Sized> NodeGrid for $ptr {
            #[inline]
            fn x0(&self) -> f64 { (**self).x0() }
            #[inline]
            fn y0(&self) -> f64 { (**self).y0() }
            #[inline]
            fn dx(&self) -> f64 { (**self).dx() }
            #[inline]
            fn dy(&self) -> f64 { (**self).dy() }
            #[inline]
            fn width(&self) -> u32 { (**self).width() }
            #[inline]
            fn height(&self) -> u32 { (**self).height() }
            #[inline]
            fn get(&self, row: i64, col: i64) -> Option<f64> { (**self).get(row, col) }
        }
    )*};
}
forward_node_grid!(&G, Box<G>, Rc<G>, Arc<G>);

/// Snap tolerance in cells (sampler.py `SNAP`).
const SNAP: f64 = 1e-9;

#[inline]
fn snap(f: f64) -> f64 {
    let k = f.round();
    if (f - k).abs() < SNAP { k } else { f }
}

/// Sample one raster at `(lat, lon)`: bilinear between pixel centres,
/// zero-weight neighbours unused, NaN if a used neighbour is nodata or
/// outside, no clamping. Port of `sampler.sample` — same operations in the
/// same order, in f64.
pub fn sample<G: NodeGrid + ?Sized>(r: &G, lat: f64, lon: f64) -> f64 {
    let fx = (lon - r.x0()) / r.dx() - 0.5;
    let fy = (r.y0() - lat) / r.dy() - 0.5;
    if !fx.is_finite() || !fy.is_finite() {
        return f64::NAN;
    }
    let fx = snap(fx);
    let fy = snap(fy);
    let c0 = fx.floor();
    let r0 = fy.floor();
    let tx = fx - c0;
    let ty = fy - r0;
    let (c0, r0) = (c0 as i64, r0 as i64);
    let use_c1 = tx != 0.0;
    let use_r1 = ty != 0.0;

    // `saturating_add`: a coordinate far outside the grid saturates at
    // `i64::MAX`, which is just as outside (`get` → None → NaN).
    let Some(v00) = r.get(r0, c0) else {
        return f64::NAN;
    };
    let mut acc = v00 * (1.0 - tx) * (1.0 - ty);
    if use_c1 {
        let Some(v01) = r.get(r0, c0.saturating_add(1)) else {
            return f64::NAN;
        };
        acc += v01 * tx * (1.0 - ty);
    }
    if use_r1 {
        let Some(v10) = r.get(r0.saturating_add(1), c0) else {
            return f64::NAN;
        };
        acc += v10 * (1.0 - tx) * ty;
    }
    if use_c1 && use_r1 {
        let Some(v11) = r.get(r0.saturating_add(1), c0.saturating_add(1)) else {
            return f64::NAN;
        };
        acc += v11 * tx * ty;
    }
    acc
}

/// JIS X 0410 secondary mesh (6-digit code) containing `(lat, lon)`. A point
/// exactly on a mesh boundary belongs to the mesh to its north / east.
///
/// Wrapping arithmetic only matters for coordinates far outside Japan (the
/// code is then meaningless, as it always was), and keeps them panic-free.
pub fn mesh6_of(lat: f64, lon: f64) -> i64 {
    let i5 = (lat * 12.0).floor() as i64;
    let j75 = ((lon - 100.0) * 8.0).floor() as i64;
    let (p, r) = (i5.div_euclid(8), i5.rem_euclid(8));
    let (q, s) = (j75.div_euclid(8), j75.rem_euclid(8));
    p.wrapping_mul(100)
        .wrapping_add(q)
        .wrapping_mul(10)
        .wrapping_add(r)
        .wrapping_mul(10)
        .wrapping_add(s)
}

/// How a product's grids combine into ΔH.
pub enum DhSelection<G> {
    /// `ΔH = sample(grid)` — a single-parameter-file product.
    Single(G),
    /// GSI's rule for the 2025 DEM re-issue (manifest `selection_rule`):
    /// `listed` inside a listed secondary mesh (NaN stays NaN), else `primary`
    /// unless that is NaN ("out of range"), else `fallback`. Each point is
    /// evaluated on one grid only; nodes are never merged.
    ListedMeshes {
        primary: G,
        listed: G,
        fallback: G,
        meshes: HashSet<i64>,
    },
}

impl<G: NodeGrid> DhSelection<G> {
    /// ΔH (metres) at `(lat, lon)`, NaN where the product has none.
    pub fn sample(&self, lat: f64, lon: f64) -> f64 {
        match self {
            Self::Single(g) => sample(g, lat, lon),
            Self::ListedMeshes {
                primary,
                listed,
                fallback,
                meshes,
            } => {
                if meshes.contains(&mesh6_of(lat, lon)) {
                    return sample(listed, lat, lon);
                }
                let v = sample(primary, lat, lon);
                if v.is_nan() {
                    sample(fallback, lat, lon)
                } else {
                    v
                }
            }
        }
    }
}

/// A [`NodeGrid`] holding only some nodes (all others read as nodata): the
/// golden-nodes fixture, which carries just the nodes the golden points
/// touch.
#[derive(Debug, Clone, PartialEq)]
pub struct SparseGrid {
    pub width: u32,
    pub height: u32,
    pub x0: f64,
    pub y0: f64,
    pub dx: f64,
    pub dy: f64,
    pub nodes: HashMap<(i64, i64), f64>,
}

impl NodeGrid for SparseGrid {
    fn x0(&self) -> f64 {
        self.x0
    }
    fn y0(&self) -> f64 {
        self.y0
    }
    fn dx(&self) -> f64 {
        self.dx
    }
    fn dy(&self) -> f64 {
        self.dy
    }
    fn width(&self) -> u32 {
        self.width
    }
    fn height(&self) -> u32 {
        self.height
    }
    fn get(&self, row: i64, col: i64) -> Option<f64> {
        if row < 0 || col < 0 || row >= self.height as i64 || col >= self.width as i64 {
            return None;
        }
        self.nodes.get(&(row, col)).copied().filter(|v| !v.is_nan())
    }
}

/// Per-request memo of ΔH grids, so members that share sample positions
/// (most COG overlays of one tile) sample the product once per pixel.
#[derive(Default)]
pub struct DhMemo {
    grids: Vec<(PixelPositions, u8, DhGrid)>,
}

impl DhMemo {
    /// The grid of tile `z/x/y` (`n × n`) at `positions`, created on first
    /// use. Keyed by positions and zoom: one composite tile's members differ
    /// only in those.
    pub fn grid(
        &mut self,
        positions: PixelPositions,
        z: u8,
        x: u32,
        y: u32,
        n: u32,
    ) -> &mut DhGrid {
        let i = match self
            .grids
            .iter()
            .position(|(p, gz, _)| *p == positions && *gz == z)
        {
            Some(i) => i,
            None => {
                self.grids
                    .push((positions, z, DhGrid::new(positions, z, x, y, n)));
                self.grids.len() - 1
            }
        };
        &mut self.grids[i].2
    }
}

/// ΔH on one tile's sample positions, evaluated lazily per pixel. Positions
/// are separable (longitude depends on the column only, latitude on the row
/// only), so both axes are precomputed once.
pub struct DhGrid {
    lons: Vec<f64>,
    lats: Vec<f64>,
    /// `INFINITY` = not evaluated yet (ΔH itself is never infinite).
    values: Vec<f64>,
}

impl DhGrid {
    pub fn new(p: PixelPositions, z: u8, x: u32, y: u32, n: u32) -> Self {
        let lons = (0..n).map(|i| p.lonlat(z, x, y, i, 0).0).collect();
        let lats = (0..n).map(|j| p.lonlat(z, x, y, 0, j).1).collect();
        Self {
            lons,
            lats,
            values: vec![f64::INFINITY; (n as usize) * (n as usize)],
        }
    }

    /// ΔH at column `i`, row `j` (NaN outside the tile).
    pub fn get<G: NodeGrid>(&mut self, selection: &DhSelection<G>, i: usize, j: usize) -> f64 {
        let (Some(&lon), Some(&lat)) = (self.lons.get(i), self.lats.get(j)) else {
            return f64::NAN;
        };
        let k = j * self.lons.len() + i;
        let Some(v) = self.values.get_mut(k) else {
            return f64::NAN;
        };
        if *v == f64::INFINITY {
            *v = selection.sample(lat, lon);
        }
        *v
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mesh6_boundaries_go_north_east() {
        assert_eq!(mesh6_of(31.5, 131.125), 473121);
        assert_eq!(mesh6_of(31.5 - 1e-9, 131.125), 473111);
        assert_eq!(mesh6_of(31.5, 131.125 - 1e-9), 473120);
        assert_eq!(mesh6_of(35.68, 139.76), 533946);
    }

    fn grid(w: u32, h: u32, f: impl Fn(i64, i64) -> Option<f64>) -> SparseGrid {
        let mut nodes = HashMap::new();
        for r in 0..h as i64 {
            for c in 0..w as i64 {
                if let Some(v) = f(r, c) {
                    nodes.insert((r, c), v);
                }
            }
        }
        SparseGrid {
            width: w,
            height: h,
            x0: 130.0,
            y0: 35.0,
            dx: 0.5,
            dy: 0.25,
            nodes,
        }
    }

    #[test]
    fn sample_is_node_bilinear_without_clamping() {
        let g = grid(3, 3, |r, c| Some((r * 10 + c) as f64));
        // Node (row 1, col 1) centre: lon 130 + 1.5·0.5, lat 35 − 1.5·0.25.
        assert_eq!(sample(&g, 35.0 - 0.375, 130.75), 11.0);
        // Midway between nodes (0,0) .. (1,1).
        assert_eq!(sample(&g, 35.0 - 0.25, 130.5), 5.5);
        // On the last node row/column: the zero-weight neighbour is unused.
        assert_eq!(sample(&g, 35.0 - 0.625, 131.25), 22.0);
        // Beyond the outer node centres: NaN, never clamped.
        assert!(sample(&g, 35.0 - 0.7, 131.25).is_nan());
        assert!(sample(&g, 35.0, 130.0).is_nan());
        // A used nodata neighbour poisons the point; an unused one does not.
        let holed = grid(3, 3, |r, c| ((r, c) != (1, 2)).then_some(1.0));
        assert!(sample(&holed, 35.0 - 0.375, 130.75 + 0.25).is_nan());
        assert_eq!(sample(&holed, 35.0 - 0.375, 130.75), 1.0);
    }

    #[test]
    fn listed_mesh_rule_selects_one_grid() {
        // Grid over lon 131.0–131.25 (east edge of mesh 473120 / 473121),
        // lat 31.5–31.75.
        let mk = |v: f64| SparseGrid {
            width: 4,
            height: 4,
            x0: 131.0,
            y0: 31.75,
            dx: 0.0625,
            dy: 0.0625,
            nodes: (0..4)
                .flat_map(|r| (0..4).map(move |c| ((r, c), v)))
                .collect(),
        };
        let mut primary = mk(1.0);
        primary.nodes.remove(&(3, 0));
        let sel = DhSelection::ListedMeshes {
            primary: &primary,
            listed: &mk(2.0),
            fallback: &mk(3.0),
            meshes: [473121].into_iter().collect(),
        };
        assert_eq!(mesh6_of(31.5625, 131.1875), 473121);
        assert_eq!(mesh6_of(31.5625, 131.09375), 473120);
        // East of 131.125 is the listed mesh 473121.
        assert_eq!(sel.sample(31.5625, 131.1875), 2.0);
        // West (473120): primary.
        assert_eq!(sel.sample(31.5625, 131.09375), 1.0);
        // Primary lacks a node of this cell: fallback, per cell.
        assert_eq!(sel.sample(31.5625, 131.0625), 3.0);
        assert!(
            DhSelection::Single(&primary)
                .sample(31.5625, 131.0625)
                .is_nan()
        );
    }

    #[test]
    fn malformed_input_does_not_panic() {
        let g = grid(2, 2, |_, _| Some(1.0));
        for (lat, lon) in [
            (f64::NAN, 0.0),
            (f64::INFINITY, 1.0),
            (1e300, -1e300),
            (-1e300, 1e300),
            (9.2e18, -9.2e18),
        ] {
            assert!(sample(&g, lat, lon).is_nan());
            let _ = mesh6_of(lat, lon);
        }
        let zero = SparseGrid {
            dx: 0.0,
            dy: -0.0,
            ..g.clone()
        };
        assert!(sample(&zero, 35.0, 130.0).is_nan());
        let mut memo = DhMemo::default();
        let sel = DhSelection::Single(&g);
        let grid = memo.grid(PixelPositions::centres(4), 3, 1, 1, 4);
        assert!(grid.get(&sel, 4, 0).is_nan());
        assert!(grid.get(&sel, 0, usize::MAX).is_nan());
        let _ = memo.grid(PixelPositions::centres(0), 255, u32::MAX, u32::MAX, 0);
    }
}
