//! The ΔH golden vectors of `tile/scripts/vertical-cogs` (generated by the
//! normative `sampler.py`) over the golden-nodes fixture: no COG reader, just
//! the nodes the points touch in a `SparseGrid`. Runs natively and in
//! wasm32 (`wasm-bindgen-test` on Node), where it must stay bit-identical.

use std::collections::HashMap;

use serde::Deserialize;
use terrain_core::hexfloat;
use terrain_core::vertical::{DhSelection, SparseGrid, mesh6_of};

#[cfg(target_arch = "wasm32")]
use wasm_bindgen_test::wasm_bindgen_test as test;

#[cfg(target_arch = "wasm32")]
macro_rules! report { ($($t:tt)*) => { wasm_bindgen_test::console_log!($($t)*) } }
#[cfg(not(target_arch = "wasm32"))]
macro_rules! report { ($($t:tt)*) => { eprintln!($($t)*) } }

const GOLDEN: &str =
    include_str!("../../../fixtures/vertical/hyokorev-jgd2011-to-jgd2024-v1.golden.json");
const NODES: &str =
    include_str!("../../../fixtures/vertical/hyokorev-jgd2011-to-jgd2024-v1.golden-nodes.json");

#[derive(Deserialize)]
struct Golden {
    product: HashMap<String, String>,
    points: usize,
    nan: usize,
    vectors: Vec<GoldenVector>,
}

#[derive(Deserialize)]
struct GoldenVector {
    label: String,
    lon_hex: String,
    lat_hex: String,
    mesh6: i64,
    dh_hex: Option<String>,
}

#[derive(Deserialize)]
struct Nodes {
    product: HashMap<String, String>,
    selection: NodesSelection,
    tr_meshes: Vec<i64>,
    grids: HashMap<String, NodesGrid>,
}

#[derive(Deserialize)]
struct NodesSelection {
    kind: String,
    primary: String,
    listed: String,
    fallback: String,
}

#[derive(Deserialize)]
struct NodesGrid {
    width: u32,
    height: u32,
    x0: String,
    y0: String,
    dx: String,
    dy: String,
    nodes: Vec<(i64, i64, Option<String>)>,
}

fn hex(s: &str) -> f64 {
    hexfloat::parse(s).unwrap_or_else(|| panic!("bad hex float {s}"))
}

fn sparse(g: &NodesGrid) -> SparseGrid {
    SparseGrid {
        width: g.width,
        height: g.height,
        x0: hex(&g.x0),
        y0: hex(&g.y0),
        dx: hex(&g.dx),
        dy: hex(&g.dy),
        nodes: g
            .nodes
            .iter()
            .filter_map(|(r, c, v)| v.as_deref().map(|v| ((*r, *c), hex(v))))
            .collect(),
    }
}

#[test]
fn golden_vectors_over_golden_nodes() {
    let golden: Golden = serde_json::from_str(GOLDEN).unwrap();
    let nodes: Nodes = serde_json::from_str(NODES).unwrap();
    // Both fixtures describe the same product files.
    assert_eq!(golden.product, nodes.product);
    assert_eq!(nodes.selection.kind, "listed-meshes");

    let grids: HashMap<&str, SparseGrid> = nodes
        .grids
        .iter()
        .map(|(name, g)| (name.as_str(), sparse(g)))
        .collect();
    let selection = DhSelection::ListedMeshes {
        primary: &grids[nodes.selection.primary.as_str()],
        listed: &grids[nodes.selection.listed.as_str()],
        fallback: &grids[nodes.selection.fallback.as_str()],
        meshes: nodes.tr_meshes.iter().copied().collect(),
    };

    let (mut bit_identical, mut nan) = (0usize, 0usize);
    for v in &golden.vectors {
        let lon = hex(&v.lon_hex);
        let lat = hex(&v.lat_hex);
        assert_eq!(mesh6_of(lat, lon), v.mesh6, "{} {lon} {lat}", v.label);
        let got = selection.sample(lat, lon);
        match &v.dh_hex {
            None => {
                assert!(
                    got.is_nan(),
                    "{}: expected NaN at {lon},{lat}, got {got}",
                    v.label
                );
                nan += 1;
            }
            Some(h) => {
                let want = hex(h);
                assert_eq!(
                    got.to_bits(),
                    want.to_bits(),
                    "{}: {lon},{lat}: got {got:e}, want {want:e}",
                    v.label
                );
                bit_identical += 1;
            }
        }
    }
    let finite = golden.vectors.len() - golden.nan;
    report!(
        "golden-nodes [{}]: {bit_identical}/{finite} finite vectors bit-identical, {nan}/{} NaN preserved",
        std::env::consts::ARCH,
        golden.nan
    );
    assert_eq!(golden.vectors.len(), golden.points);
    assert_eq!((bit_identical, nan), (finite, golden.nan));
    assert_eq!((finite, golden.nan), (2510, 1468));
}
