name = "plateau-tiles"
main = "src/index.ts"
compatibility_date = "2025-05-01"
workers_dev = false

routes = [
  { pattern = "tiles.plateau.city/*", zone_name = "plateau.city" },
]

[[r2_buckets]]
binding = "TERRAIN_BUCKET"
bucket_name = "plateau-terrain"

[observability]
enabled = true
