name: build-worker
on:
  workflow_call:
    outputs:
      image:
        value: ${{ jobs.docker.outputs.image }}
jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/eukarya-inc/plateau-view/plateauview-api-worker:latest
    outputs:
      image: ${{ env.IMAGE_NAME }}@sha256:${{ steps.docker.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and load docker image
        uses: docker/build-push-action@v3
        id: docker
        with:
          file: worker/Dockerfile
          platforms: linux/amd64
          load: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
