name: build-tiles
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true
jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/eukarya-inc/plateau-view/plateauview-tiles:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./tiles
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
