name: build-server
on:
  workflow_call:
    outputs:
      image:
        value: ${{ jobs.build-server.outputs.image }}
      latest_tag:
        value: ${{ jobs.build-server.outputs.latest_tag }}

jobs:
  build-server:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/eukarya-inc/plateau-view/plateauview-api
      EXTENSION_IMAGE: ghcr.io/eukarya-inc/plateau-view/plateauview-extension:latest
    outputs:
      image: ${{ steps.set-tags.outputs.build_tag }}
      latest_tag: ${{ steps.set-tags.outputs.latest_tag }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set tags
        id: set-tags
        run: |
          echo "build_tag=${{ env.IMAGE_NAME }}:build-${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "latest_tag=${{ env.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download extension artifact
        continue-on-error: true
        run: |
          docker pull "$EXTENSION_IMAGE"
          CID=$(docker create "$EXTENSION_IMAGE" /)
          docker cp "$CID":/dist .
          docker rm "$CID"
          shopt -s dotglob
          mv dist/* .
          rmdir dist
      - name: Build and push docker image with temporary tag
        uses: docker/build-push-action@v3
        id: docker
        with:
          context: ./server
          platforms: linux/amd64
          tags: ${{ steps.set-tags.outputs.build_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
