name: ci-server
on:
  workflow_call:
jobs:
  ci-server-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64
          working-directory: server
          args: --timeout=5m
  ci-server-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: server/go.sum
      - name: test
        working-directory: server
        run: go test ./... -v -race -tags draco
