name: ci-tile
on:
  workflow_call:
jobs:
  ci-tile-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: "1.92"
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: tile
      - name: Check formatting
        working-directory: tile
        run: cargo fmt --all -- --check
      - name: Clippy
        working-directory: tile
        run: cargo clippy --all-targets -- -D warnings
  ci-tile-test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: "1.92"
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: tile
      - name: Test
        working-directory: tile
        run: cargo test --all-targets
  ci-tile-check:
    runs-on: ubuntu-latest
    needs: [ci-tile-lint, ci-tile-test]
    if: always()
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2
        with:
          egress-policy: audit
      - name: Check if all jobs succeeded
        run: |
          if [[ "${{ needs.ci-tile-lint.result }}" != "success" ]] || [[ "${{ needs.ci-tile-test.result }}" != "success" ]]; then
            echo "Lint or test failed"
            exit 1
          fi
