name: ci-tools
on:
  workflow_call:
    inputs:
      release_tools:
        type: string
jobs:
  ci-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: tools -> tools/plateau-view-tool/target
      - uses: giraffate/clippy-action@13b9d32482f25d29ead141b79e7e04e7900281e0 # v1.0.1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: tools/plateau-view-tool
      - name: test
        working-directory: tools/plateau-view-tool
        run: cargo test --all

  ci-tools-build:
    needs: ci-tools
    name: ci-server-build - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: plateau-view-tool.exe
            name: plateau-view-tool-Windows-x86_64.zip

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: plateau-view-tool
            name: plateau-view-tool-Darwin-x86_64.tar.gz

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: tools -> tools/plateau-view-tool/target
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@a8cc74d61047fa553b4e908b4b10e70029f00ca6 # v1.0.6
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
          working-directory: tools/plateau-view-tool
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.platform.name }}
          path: tools/plateau-view-tool/target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
          if-no-files-found: error

  ci-tools-release:
    runs-on: ubuntu-latest
    needs: ci-tools-build
    if: inputs.release_tools == 'true'
    steps:
      - name: Set up git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: tools-artifacts
      - name: Pack tools
        run: |
          mkdir -p tools-artifacts/tools
          tree tools-artifacts
          tar -czf tools-artifacts/tools/plateau-view-tool-Darwin-x86_64.tar.gz tools-artifacts/plateau-view-tool-Darwin-x86_64.tar.gz/plateau-view-tool
          zip -r tools-artifacts/tools/plateau-view-tool-Windows-x86_64.zip tools-artifacts/plateau-view-tool-Windows-x86_64.zip/plateau-view-tool.exe
      - name: Push tools tag
        run: |
          git tag -f tools
          git push -f --tags
      - run: tree tools-artifacts
      - name: Update Github Release with artifacts
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          artifacts: tools-artifacts/tools/*
          tag: tools
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
