name: ci-worker
on:
  workflow_call:
jobs:
  ci-worker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: worker/go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          # Don't forget to update ci-server.yml also
          version: v2.7
          working-directory: worker
          args: --timeout=5m
  ci-worker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: worker/go.mod
          cache-dependency-path: worker/go.sum
      - name: test
        working-directory: worker
        run: go test ./... -v -race
  ci-worker-check:
    runs-on: ubuntu-latest
    needs: [ci-worker-lint, ci-worker-test]
    if: always()
    steps:
      - name: Check if all jobs succeeded
        run: |
          if [[ "${{ needs.ci-worker-lint.result }}" != "success" ]] || [[ "${{ needs.ci-worker-test.result }}" != "success" ]]; then
            echo "Lint or test failed"
            exit 1
          fi
