name: ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      extension: ${{ steps.extension.outputs.any_changed }}
      server: ${{ steps.server.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: changed files for extension
        id: extension
        uses: tj-actions/changed-files@v36
        with:
          files: |
            extension
            .github/workflows/ci.yml
            .github/workflows/ci-extension.yml
            .github/workflows/ci-extension-version-update.yml
      - name: changed files for server
        id: server
        uses: tj-actions/changed-files@v36
        with:
          files: |
            server
            .github/workflows/ci.yml
            .github/workflows/ci-server.yml
            .github/workflows/build-server.yml
            .github/workflows/deploy-server-dev.yml
            .github/workflows/deploy-server-prod.yml
      - name: changed files for geo
        id: geo
        uses: tj-actions/changed-files@v36
        with:
          files: |
            geo
            .github/workflows/ci.yml
            .github/workflows/ci-geo.yml
            # .github/workflows/build-geo.yml
            # .github/workflows/deploy-geo-dev.yml
            # .github/workflows/deploy-geo-prod.yml
  # ci-extension-version-update:
  #   needs: prepare
  #   if: ${{ !failure() && needs.prepare.outputs.extension == 'true' && github.event_name == 'push' && github.ref_name == 'main' }}
  #   uses: ./.github/workflows/ci-extension-version-update.yml
  #   with:
  #     commit-sha: ${{ github.sha }}
  ci-extension:
    needs:
      - prepare
      # - ci-extension-version-update
    if: ${{ !failure() && needs.prepare.outputs.extension == 'true' }}
    uses: ./.github/workflows/ci-extension.yml
  ci-server:
    needs: prepare
    if: needs.prepare.outputs.server == 'true'
    uses: ./.github/workflows/ci-server.yml
  ci-geo:
    needs: prepare
    if: needs.prepare.outputs.geo == 'true'
    uses: ./.github/workflows/ci-geo.yml
  ci:
    runs-on: ubuntu-latest
    needs:
      - ci-extension
      - ci-server
    if: '!failure()'
    steps:
      - run: echo OK
  # build-server:
  #   needs: ci-server
  #   if: ${{ success() && github.event_name == 'push' && github.ref_name == 'main' }}
  #   uses: ./.github/workflows/build-server.yml
  # deploy-server-dev:
  #   needs: build-server
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dispatch deployment
  #       uses: peter-evans/repository-dispatch@v2
  #       with:
  #         event-type: deploy-server-dev
