name: ⭐️ Deploy PLATEAU Server dev
on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-server-dev]
env:
  IMAGE: ghcr.io/eukarya-inc/plateau-view/plateauview-api:latest
  IMAGE_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau-dev/reearth-plateau/plateauview-api:latest
jobs:
  deploy_server:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW'
    environment: dev
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download server arfiacts
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml
          workflow_conclusion: success
          branch: main
          name: plateauview-api
          check_artifacts: true
      - name: Unpack docker image
        run: docker load < plateauview-api.tar.gz
      - name: docker push
        run: |
          docker tag $IMAGE $IMAGE_GCP && \
          docker push $IMAGE &&
          docker push $IMAGE_GCP
      - name: Deploy server to Cloud Run
        run: |
          gcloud run deploy plateauview-api \
            --image $IMAGE_GCP \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --quiet
