name: ⭐️ Deploy PLATEAU AR dev
on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-ar-dev]
env:
  GCS_DEST: gs://plateau-dev-reearth-ar-bucket
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/383489516390/locations/global/workloadIdentityPools/github-actions-oidc/providers/github-provider
  GCP_REGION: asia-northeast1
jobs:
  deploy_ar:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0'
    defaults:
      run:
        working-directory: ar
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          branch: main
          workflow: ci.yml
          name: ar
          path: ar/dist
          check_artifacts: true
          search_artifacts: true
      - name: Deploy
        run: gsutil -m -h "Cache-Control:no-store" rsync -dr dist ${{ env.GCS_DEST }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ar
          path: ar/dist/**/*
