name: 🌊 Deploy Re:earth Flow Production Environment
on:
  workflow_dispatch:
    inputs:
      web_run_id:
        type: string
        description: Deploy the specific version of web to specify the run ID. If specified, deployment of the server will be skipped. (Optional)
        required: false
env:
  IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/plateau-view-3.0/reearth-flow-api:latest
  IMAGE_NAME_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau/reearth-plateau/reearth-flow-api:latest
  IMAGE_NAME_HUB: eukarya/plateauview2-reearth-flow-api:latest

  WEB_IMAGE_NAME: reearth/reearth-flow-web:nightly
  WEB_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/plateau-view-3.0/reearth-flow-web:latest
  WEB_IMAGE_NAME_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau/reearth-plateau/reearth-flow-web:latest

  WS_IMAGE_NAME: reearth/reearth-flow-websocket:nightly
  WS_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/plateau-view-3.0/reearth-flow-websocket:latest
  WS_IMAGE_NAME_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau/reearth-plateau/reearth-flow-websocket:latest
  WS_IMAGE_NAME_HUB: eukarya/plateauview2-reearth-flow-websocket:latest

  WORKER_IMAGE_NAME: reearth/reearth-flow-worker:nightly
  WORKER_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/plateau-view-3.0/reearth-flow-worker:latest
  WORKER_IMAGE_NAME_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau/reearth-plateau/reearth-flow-worker:latest
  WORKER_IMAGE_NAME_HUB: eukarya/plateauview2-reearth-flow-worker:latest

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy_server:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      id-token: write
      packages: read
    if: ${{ !github.event.inputs.web_run_id && github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0' }}
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker image
        run: docker pull $IMAGE_NAME_GHCR
      - name: Push docker image
        run: docker tag $IMAGE_NAME_GHCR $IMAGE_NAME_GCP && docker push $IMAGE_NAME_GCP
      - name: Deploy
        run: |
          gcloud run deploy reearth-flow-api \
            --image $IMAGE_NAME_GCP \
            --region $GCP_REGION \
            --platform managed \
            --quiet
        env:
          GCP_REGION: ${{ vars.GCP_REGION }}

  deploy_web:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0'
    environment: prod
    permissions:
      id-token: write
      packages: write
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker images
        run: docker pull $WEB_IMAGE_NAME
      - name: Tag docker images
        run: docker tag $WEB_IMAGE_NAME $WEB_IMAGE_NAME_GHCR && docker tag $WEB_IMAGE_NAME $WEB_IMAGE_NAME_GCP
      - name: Push docker images
        run: docker push $WEB_IMAGE_NAME_GHCR && docker push $WEB_IMAGE_NAME_GCP
      - name: Deploy
        run: |
          gcloud run deploy reearth-flow-web \
            --image $WEB_IMAGE_NAME_GCP \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --quiet

  deploy_websocket:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0'
    environment: prod
    permissions:
      id-token: write
      packages: write
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker image
        run: docker pull $WS_IMAGE_NAME
      - name: Push docker image
        run: docker tag $WS_IMAGE_NAME_GHCR $WS_IMAGE_NAME_GCP && docker push $WS_IMAGE_NAME_GCP
      - name: Deploy
        run: |
          gcloud run deploy reearth-flow-websocket \
            --image $WS_IMAGE_NAME_GCP \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --quiet

  deploy_worker:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0'
    environment: prod
    permissions:
      id-token: write
      packages: write
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker image
        run: docker pull $WORKER_IMAGE_NAME_GHCR
      - name: Push docker image
        run: docker tag $WORKER_IMAGE_NAME_GHCR $WORKER_IMAGE_NAME_GCP && docker push $WORKER_IMAGE_NAME_GCP

  push_hub:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    if: ${{ github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0' }}
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: docker pull $IMAGE_NAME_GHCR
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image
        run: docker tag $IMAGE_NAME_GHCR $IMAGE_NAME_HUB && docker push $IMAGE_NAME_HUB
      - name: Pull websocket image
        run: docker pull $WS_IMAGE_NAME_GHCR
      - name: Push websocket image
        run: docker tag $WS_IMAGE_NAME_GHCR $WS_IMAGE_NAME_HUB && docker push $WS_IMAGE_NAME_HUB
      - name: Pull worker image
        run: docker pull $WORKER_IMAGE_NAME_GHCR
      - name: Push worker image
        run: docker tag $WORKER_IMAGE_NAME_GHCR $WORKER_IMAGE_NAME_HUB && docker push $WORKER_IMAGE_NAME_HUB
