name: ⭐︎ Deploy reearth visualizer production
on:
  workflow_dispatch:
    inputs:
      web_run_id:
        type: string
        description: Deploy the specific version of web to specify the run ID. If specified, deployment of the server will be skipped. (Optional)
        required: false
env:
  # TODO: Remove after migrating to Cloud Run
  GCS_DEST: gs://plateau-prod-reearth-visualizer-static-bucket

  IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/plateau-view-3.0/reearth-visualizer-api:latest
  IMAGE_NAME_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau/reearth-plateau/reearth-visualizer-api:latest
  IMAGE_NAME_HUB: eukarya/plateauview2-reearth-visualizer-api:latest

  WEB_IMAGE_NAME: reearth/reearth-visualizer-web:nightly
  WEB_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/plateau-view-3.0/reearth-visualizer-web:latest
  WEB_IMAGE_NAME_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau/reearth-plateau/reearth-visualizer-web:latest
concurrency:
  group: ${{ github.workflow }}
jobs:
  # TODO: Remove after migrating to Cloud Run
  deploy_web_gcs:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0'
    environment: prod
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          workflow: deploy-reearth-visualizer-dev.yml
          branch: ${{ !github.event.inputs.web_run_id && 'main' || '' }}
          name: reearth-visualizer-web
          check_artifacts: true
          search_artifacts: true
          run_id: ${{ github.event.inputs.web_run_id }}
      - name: Extract
        run: tar -xvf reearth-visualizer-web.tar.gz
      - name: Deploy
        run: gsutil -m -h "Cache-Control:no-store" rsync -x "^cloud/.*$|^reearth_config\\.json$|^extension/.*$" -dr reearth-web/ ${{ env.GCS_DEST }}
      # TODO: purge CDN cache
  deploy_server:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      id-token: write
      packages: read
    if: ${{ !github.event.inputs.web_run_id && github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0' }}
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker image
        run: docker pull $IMAGE_NAME_GHCR
      - name: Push docker image
        run: docker tag $IMAGE_NAME_GHCR $IMAGE_NAME_GCP && docker push $IMAGE_NAME_GCP
      - name: Deploy
        run: |
          gcloud run deploy reearth-visualizer-api \
            --image $IMAGE_NAME_GCP \
            --region $GCP_REGION \
            --platform managed \
            --quiet
        env:
          GCP_REGION: ${{ vars.GCP_REGION }}

  deploy_web:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0'
    environment: prod
    permissions:
      id-token: write
      packages: write
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker images
        run: docker pull $WEB_IMAGE_NAME
      - name: Tag docker images
        run: docker tag $WEB_IMAGE_NAME $WEB_IMAGE_NAME_GHCR && docker tag $WEB_IMAGE_NAME $WEB_IMAGE_NAME_GCP
      - name: Push docker images
        run: docker push $WEB_IMAGE_NAME_GHCR && docker push $WEB_IMAGE_NAME_GCP
      - name: Deploy
        run: |
          gcloud run deploy reearth-visualizer-web \
            --image $WEB_IMAGE_NAME_GCP \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --quiet

  push_hub:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    if: ${{ github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0' }}
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: docker pull $IMAGE_NAME_GHCR
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image
        run: docker tag $IMAGE_NAME_GHCR $IMAGE_NAME_HUB && docker push $IMAGE_NAME_HUB
