name: ⭐️ Deploy PLATEAU Worker production
on:
  workflow_dispatch:
  workflow_call:
env:
  IMAGE: ghcr.io/eukarya-inc/plateau-view/plateauview-api-worker:latest
  IMAGE_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau/reearth-plateau/plateauview-api-worker:latest
  IMAGE_HUB: eukarya/plateauview-api-worker:latest
concurrency:
  group: ${{ github.workflow }}
jobs:
  deploy_worker:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW'
    environment: prod
    permissions:
      contents: read
      id-token: write
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Pull docker image from GHCR
        run: docker pull $IMAGE
      - name: docker push
        run: |
          docker tag $IMAGE $IMAGE_GCP
          docker push $IMAGE_GCP
          docker tag $IMAGE $IMAGE_HUB
          docker push $IMAGE_HUB
