name: ⭐️ Deploy PLATEAU Server production
on:
  workflow_call:
  workflow_dispatch:
env:
  IMAGE: ghcr.io/eukarya-inc/plateau-view/plateauview-api:latest
  IMAGE_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau/reearth-plateau/plateauview-api:latest
  IMAGE_HUB: eukarya/plateauview-api:latest
jobs:
  deploy_server:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW'
    environment: prod
    permissions:
      contents: read
      id-token: write
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 10
          command: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull docker image from GHCR
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 10
          command: docker pull $IMAGE
      - name: docker push
        run: |
          docker tag $IMAGE $IMAGE_GCP
          docker push $IMAGE_GCP
      - name: Deploy server to Cloud Run
        run: |
          gcloud run deploy plateauview-api \
            --image $IMAGE_GCP \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --quiet
      - name: Deploy server job to Cloud Run
        run: |
          gcloud run jobs deploy plateauview-server-job \
            --image $IMAGE_GCP \
            --region ${{ vars.GCP_REGION }} \
            --quiet

  push_hub:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Log in to GitHub Container Registry
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 10
          command: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull image
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 10
          command: docker pull $IMAGE
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image
        run: docker tag $IMAGE $IMAGE_HUB && docker push $IMAGE_HUB
