name: ⭐️ Deploy PLATEAU Extension prod
on:
  workflow_dispatch:
env:
  GCS_DEST: gs://plateau-prod-reearth-app-bucket
  GCP_SERVICE_ACCOUNT: github-cicd-oidc@reearth-plateau.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/232353765693/locations/global/workloadIdentityPools/github-actions-oidc/providers/github-provider
  GCP_REGION: asia-northeast1
  PLATEAU_GEO_API: https://geo.plateau.reearth.io
jobs:
  deploy_extension:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0'
    permissions:
      contents: read
      id-token: write
      packages: write
    defaults:
      run:
        working-directory: extension
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Build
        run: yarn build
      - name: Deploy
        run: gsutil -m -h "Cache-Control:no-store" rsync -dr dist ${{ env.GCS_DEST }}/extension
