name: 🌊 Deploy Re:earth Flow Development Environment
on:
  workflow_dispatch:
env:
  API_IMAGE_NAME: reearth/reearth-flow-api:nightly
  API_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/PLATEAU-VIEW/reearth-flow-api:latest
  API_IMAGE_NAME_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau-dev/reearth-plateau/reearth-flow-api:latest

  SUBSCRIBER_IMAGE_NAME: reearth/reearth-flow-subscriber:nightly
  SUBSCRIBER_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/PLATEAU-VIEW/reearth-flow-subscriber:latest
  SUBSCRIBER_IMAGE_NAME_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau-dev/reearth-plateau/reearth-flow-subscriber:latest

  WEB_IMAGE_NAME: reearth/reearth-flow-web:nightly
  WEB_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/PLATEAU-VIEW/reearth-flow-web:latest
  WEB_IMAGE_NAME_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau-dev/reearth-plateau/reearth-flow-web:latest

  WS_IMAGE_NAME: reearth/reearth-flow-websocket:nightly
  WS_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/PLATEAU-VIEW/reearth-flow-websocket:latest
  WS_IMAGE_NAME_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau-dev/reearth-plateau/reearth-flow-websocket:latest

  WORKER_IMAGE_NAME: reearth/reearth-flow-worker:nightly
  WORKER_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/PLATEAU-VIEW/reearth-flow-worker:latest
  WORKER_IMAGE_NAME_GCP: asia-northeast1-docker.pkg.dev/reearth-plateau-dev/reearth-plateau/reearth-flow-worker:latest

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy_api:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      packages: write
    if: ${{ github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW' }}
    steps:
      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker images
        run: docker pull $API_IMAGE_NAME
      - name: Tag docker images
        run: docker tag $API_IMAGE_NAME $API_IMAGE_NAME_GHCR && docker tag $API_IMAGE_NAME $API_IMAGE_NAME_GCP
      - name: Push docker images
        run: docker push $API_IMAGE_NAME_GHCR && docker push $API_IMAGE_NAME_GCP
      - name: Deploy
        run: |
          gcloud run deploy reearth-flow-api \
            --image $API_IMAGE_NAME_GCP \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --quiet

  deploy_web:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW'
    environment: dev
    permissions:
      id-token: write
      packages: write
    steps:
      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker images
        run: docker pull $WEB_IMAGE_NAME
      - name: Tag docker images
        run: docker tag $WEB_IMAGE_NAME $WEB_IMAGE_NAME_GHCR && docker tag $WEB_IMAGE_NAME $WEB_IMAGE_NAME_GCP
      - name: Push docker images
        run: docker push $WEB_IMAGE_NAME_GHCR && docker push $WEB_IMAGE_NAME_GCP
      - name: Deploy
        run: |
          gcloud run deploy reearth-flow-web \
            --image $WEB_IMAGE_NAME_GCP \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --quiet

  deploy_subscriber:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW'
    environment: dev
    permissions:
      id-token: write
      packages: write
    steps:
      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker images
        run: docker pull $SUBSCRIBER_IMAGE_NAME
      - name: Tag docker images
        run: docker tag $SUBSCRIBER_IMAGE_NAME $SUBSCRIBER_IMAGE_NAME_GHCR && docker tag $SUBSCRIBER_IMAGE_NAME $SUBSCRIBER_IMAGE_NAME_GCP
      - name: Push docker images
        run: docker push $SUBSCRIBER_IMAGE_NAME_GHCR && docker push $SUBSCRIBER_IMAGE_NAME_GCP
      - name: Deploy
        run: |
          gcloud run deploy reearth-flow-subscriber \
            --image $SUBSCRIBER_IMAGE_NAME_GCP \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --quiet

  deploy_websocket:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW'
    environment: dev
    permissions:
      id-token: write
      packages: write
    steps:
      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker images
        run: docker pull $WS_IMAGE_NAME
      - name: Tag docker images
        run: docker tag $WS_IMAGE_NAME $WS_IMAGE_NAME_GHCR && docker tag $WS_IMAGE_NAME $WS_IMAGE_NAME_GCP
      - name: Push docker images
        run: docker push $WS_IMAGE_NAME_GHCR && docker push $WS_IMAGE_NAME_GCP
      - name: Deploy
        run: |
          gcloud run deploy reearth-flow-websocket \
            --image $WS_IMAGE_NAME_GCP \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --quiet

  deploy_worker:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW'
    environment: dev
    permissions:
      id-token: write
      packages: write
    steps:
      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker images
        run: docker pull $WORKER_IMAGE_NAME
      - name: Tag docker images
        run: docker tag $WORKER_IMAGE_NAME $WORKER_IMAGE_NAME_GHCR && docker tag $WORKER_IMAGE_NAME $WORKER_IMAGE_NAME_GCP
      - name: Push docker images
        run: docker push $WORKER_IMAGE_NAME_GHCR && docker push $WORKER_IMAGE_NAME_GCP
