name: E2E CMS Web dev
on:
  workflow_call:
    inputs:
      api:
        required: true
        type: string
      baseUrl:
        required: true
        type: string
    secrets:
      REEARTH_PROD_E2E_EMAIL:
        required: true
      REEARTH_PROD_E2E_PASSWORD:
        required: true
jobs:
  call-workflow:
    uses: reearth/reearth-cms/.github/workflows/e2e_web.yml@main
    with:
      api: ${{ inputs.api }}
      baseUrl: ${{ inputs.baseUrl }}
    secrets:
      REEARTH_WEB_E2E_USERNAME: ${{ secrets.REEARTH_PROD_E2E_EMAIL }}
      REEARTH_WEB_E2E_PASSWORD: ${{ secrets.REEARTH_PROD_E2E_PASSWORD }}
