name: Pack
on:
  workflow_dispatch:
  pull_request: # debug
    branches: pack
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: plateau
          path: plateau
      - name: Delete files without .git in the repo
        run: |
          find . -type f -not -path '*/.git/*' -not -name '.git' -delete
      - name: Extract PLATEAU-VIEW-3.0 zip
        run: |
          wget https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/archive/refs/heads/main.zip
          unzip main.zip
          mv PLATEAU-VIEW-3.0-main/* plateau
      - name: Extract PLATEAU-VIEW-AR zip
        run: |
          wget https://github.com/eukarya-inc/PLATEAU-VIEW-AR/archive/refs/heads/main.zip
          unzip main.zip
          mv PLATEAU-VIEW-AR-main plateau/ar
      - name: Extract Re:Earth zip
        run: |
          wget https://github.com/reearth/reearth/archive/refs/heads/main.zip
          unzip main.zip
          mv reearth-main plateau/editor
      - name: Extract Re:Earth CMS zip
        run: |
          wget https://github.com/reearth/reearth-cms/archive/refs/heads/main.zip
          unzip main.zip
          mv reearth-cms-main plateau/cms
      - name: Print tree of plateau
        run: |
          tree plateau
      # - name: Commit and push
      #   working-directory: plateau
      #   run: |
      #     git config --local user.name github-actions
      #     git config --local user.email github-actions@github.com
      #     git add .
      #     git commit -m "Update"
      #     git push
