name: Pack
on:
  workflow_dispatch:
  push: # debug
    branches: pack
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: plateau
          path: plateau
      - name: Clean the repo except .git
        run: find plateau -type f -not -path '.git/*' -delete; tree -a
      - name: Extract PLATEAU-VIEW-3.0 zip
        run: |
          wget https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/archive/refs/heads/main.zip
          unzip main.zip
          shopt -s dotglob
          mv PLATEAU-VIEW-3.0-main/* plateau/
          rmdir PLATEAU-VIEW-3.0-main
          rm main.zip
      - name: Extract PLATEAU-VIEW-AR zip
        run: |
          wget https://github.com/eukarya-inc/PLATEAU-VIEW-AR/archive/refs/heads/main.zip
          unzip main.zip
          shopt -s dotglob
          mv PLATEAU-VIEW-AR-main plateau/ar
          rm main.zip
      - name: Extract Re:Earth zip
        run: |
          wget https://github.com/reearth/reearth/archive/refs/heads/main.zip
          unzip main.zip
          shopt -s dotglob
          mv reearth-main plateau/editor
          rm main.zip
      - name: Extract Re:Earth CMS zip
        run: |
          wget https://github.com/reearth/reearth-cms/archive/refs/heads/main.zip
          unzip main.zip
          shopt -s dotglob
          mv reearth-cms-main plateau/cms
          rm main.zip
      - run: tree -a
      - name: Commit and push
        run: |
          cd plateau
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo commit
          git commit -m "Update" -a
          echo push
          git push
